---
- name: copy script
  hosts: webservers

  tasks:
          - name: copying script file
              copy:
                src: "{{ item.src }}"
                dest: "{{ item.dest }}"
                remote_src: true
              loop:
                - {src: '/root/scripts/loadtest.sh', dest: '/root/scripts/'}
              become: true
