---
- name: scheduling a cronjobs
  hosts: webservers

  tasks:
          - name: "##Crontab entry via ansible"
            cron:
                    name: "##Crontab entry via ansible"    
                    minute: "*"
                    hour: "*"
                    day: "*"
                    month: "*"
                    weekday: "*"
                    job: "/root/scripts/loadtest.sh"
