---
- name: copy script
- hosts: 192.168.0.112
  tasks:
  - name: transfer data from machine1 to machine2

    copy:
     src: /root/scripts/loadtest.sh
     dest: /root/scripts/

    delegate_to: 192.168.0.114
