---
- name: copy script
  hosts: webservers

  tasks:
          - name: copying script file
            copy:
                    src: /root/scripts/loadtest.sh
                    dest: /root/scripts/
                    owner: root
                    group: root
                    mode: 0777
		                remote_src: true
		                become: true
