---
- name: copy script
  hosts: 192.168.1.8

  tasks:
          - name: copying script file
            become: true
            copy:
                    src: /root/scripts/loadtest.sh
                    dest: /root/scripts/
                    owner: root
                    group: root
                    mode: 0644

          - name: "##Crontab entry via ansible"
            cron:
                    name: "##Crontab entry via ansible"
                    minute: "*"
                    hour: "*"
                    day: "*"
                    month: "*"
                    weekday: "*"
                    job: "/root/scripts/loadtest.sh"
