---
- name: copy script
- hosts: source_system
  tasks:
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /root/scripts/loadtest.sh
        dest: /root/scripts/
        mode: pull
      delegate_to: deployee_system
